import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { exec } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = (process.argv[2] === "production");

// Repomix Call
const repomixPlugin = {
	name: 'repomix-runner',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				console.log("Build finished! Running repomix...");
				exec('npx repomix --ignore "pptx-preview/**,node_modules/**,.git/**,main.js"', (error, stdout, stderr) => {
					if (error) {
						console.error(`Repomix error: ${error.message}`);
						return;
					}
					if (stderr) console.error(`Repomix stderr: ${stderr}`);
					console.log("Repomix updated successfully.");
				});
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [repomixPlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}